### ISSUE TITLE
a卡搞起啊, gogogo ~

### ISSUE THREAD

**Issue by yukminnie** [YiWeiHuang-stack/Squirrel-RIFE#10]
如题.

**Comment by ABlyh-LEO** [comment]
目前主要的开发者都处于开学状态。本人九年级，项目的发起者高二，学习压力都非常大，更新缓慢还请谅解。

**Comment by ABlyh-LEO** [comment]
如果急用，可以考虑RIFEGUI

**Comment by yukminnie** [comment]
> 如果急用，可以考虑RIFEGUI

哇，高中生啊😊臭弟弟们现在这么厉害了嘛（doge，谢谢，我去研究一下
