### ISSUE TITLE
开启一拍三后补帧卡死（与是否开启转场识别无关）

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#111]
![image](https://user-images.githubusercontent.com/59187833/125161139-2de04480-e1b3-11eb-9d92-39ee54142baf.png)
补帧信息
![image](https://user-images.githubusercontent.com/59187833/125161146-40f31480-e1b3-11eb-9001-d3eff9288a18.png)
内存占用异常信息（浅绿色为内存占用，本机内存大小为32G，缓存分配为自动）
![00000001](https://user-images.githubusercontent.com/59187833/125161193-7f88cf00-e1b3-11eb-94f3-35f813b6006c.png)
卡死位置：你的名字片尾字幕出现前
该资源已补帧多次，且3.3.2版本时使用anime_sharp模型开启一拍三未出现卡死情况

**Comment by Justin62628** [comment]
1. 都是超过三帧的黑帧
2. anime smooth
3. Cutella  
@yhrbjsy 你还记得是启动了多久之后开始炸内存了吗？3.4.0
3.4.0的几次炸内存都是在一个多小时后
4. 不过貌似队列走完后也就恢复了，最终没炸掉

- [ ] 3.4.0单一识别炸了

**Comment by Justin62628** [comment]
3.3.3 单一识别没问题

**Comment by Justin62628** [comment]
3.4.1 alpha添加了纯色帧特判，应该不会卡了
