### ISSUE TITLE
批处理时补完第二个视频导出帧率错误

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [YiWeiHuang-stack/Squirrel-RIFE#118]
版本:3.4.profession
两个视频均设置4x帧率，对应的config文件中，target_fps也等于23.976*4 = 95.904
可第二个视频导出之后是48的帧率(貌似读了之前补帧的配置文件(补帧的文件还不是同一个))
但除了帧率其他设置都是匹配的

**Comment by Justin62628** [comment]
经复现无此bug，需要更多设置信息
