### ISSUE TITLE
你们好呀，可以集成下我做的 rife-ncnn-vulkan 吗？

### ISSUE THREAD

**Issue by nihui** [YiWeiHuang-stack/Squirrel-RIFE#2]
这是 github

https://github.com/nihui/rife-ncnn-vulkan

支持 intel amd nvidia 显卡
支持 windows linux macos
exe很小的～

**Comment by YiWeiHuang-stack** [comment]
感谢大佬关注我们的应用，我想知道rife-ncnn-vulkan是否可以加入指定2x,4x,8x帧数，方便结合抽帧操作，提升画面流畅度

**Comment by nihui** [comment]
只能2x，没有做4x 8x

**Comment by YiWeiHuang-stack** [comment]
只有2x可以，我以为默认只有4x 😂

**Comment by Justin62628** [comment]
SVFI2.0终于集成了，现在支持2**exp倍率了，感谢nihui大佬

**Comment by YiWeiHuang-stack** [comment]
能支持管道就更好了😀
