### ISSUE TITLE
缩小文件体积

### ISSUE THREAD

**Issue by yxtj** [YiWeiHuang-stack/Squirrel-RIFE#3]
1，请提高python打包技术。
下载的时候就感觉怎么会这么大不会是打包了一个完整的pytorch吧。下载之后我发现还真是，而且还有很多不需要的包，比如matplotlib, ipython, scipy, tcl 甚至还有jedi, sqlite和win32com。
另外pytorch是可以裁剪的，而且RIFE用到的模块不多，可以大幅裁剪。
而且__pychche__目录也应该清理掉，或者只保留对应打包的python版本的缓存，现在里面有两个python版本的缓存文件。

2，裁剪掉第三方依赖的冗余部分。
比如我发现了好几份opencv。ffmpeg附带的那么多exe工具也用不到。

3，提供打包python环境的和不打包的两种版本。
很多人是有配置好的anaconda环境的，你让他们再下载一份是明显的浪费。可以提供两个版本，其中不打包的版本需要用户指定python路径。并且提供一份依赖列表和使用conda/pip安装依赖的命令脚本。为了保险起见，可以让程序启动的时候检查依赖库和版本。

4，分离程序文件和数据文件。
训练好的模型文件，RIFE的模型部分对于你们这个project来说是不需要更新的，可以考虑把他们独立出来，单独提供下载。

**Comment by ABlyh-LEO** [comment]
感谢您提出的宝贵意见，我们将在之后的版本进行改进

**Comment by yxtj** [comment]
> 感谢您提出的宝贵意见，我们将在之后的版本进行改进
加油。
我初步估计，裁剪之后，解压完的大小可以控制在1G之内，做的好的话500M也有可能。
希望你们能把界面部分也开源了。
