### ISSUE TITLE
不支持中文路径

### ISSUE THREAD

**Issue by Justin62628** [YiWeiHuang-stack/Squirrel-RIFE#32]
岂有此理！
- print改logger，封装好
- 函数变量类型归一化

**Comment by NULL204** [comment]
还有空格也是一样的。。。

**Comment by Justin62628** [comment]
空格问题：读取ffmpeg导出的txt路径未加双引号

**Comment by Justin62628** [comment]
- 特殊字符（日文）导致软件界面卡死问题
- one line shot 输出unicode编码错误
- 错误提示

**Comment by Justin62628** [comment]
SVFI 3.2.2/3 Needing further Inspection
