### ISSUE TITLE
尝试使用正弦波频率估计的改进Rife算法

### ISSUE THREAD

**Issue by NULL204** [YiWeiHuang-stack/Squirrel-RIFE#36]
尝试使用正弦波频率估计的改进Rife算法
https://wenku.baidu.com/view/2d3fed21fc4ffe473368ab97.html
https://download.csdn.net/download/lovener_0/4668525
https://xueshu.baidu.com/usercenter/paper/show?paperid=77770fa16f51dbf976b2d67dacdbbde5&site=xueshu_se
https://xueshu.baidu.com/usercenter/paper/show?paperid=a8b092ea64c11a97c00249b5ff6e9abd&site=xueshu_se
https://xueshu.baidu.com/usercenter/paper/show?paperid=e5d7ab8bdb3acad11bd425ffff71eafe&site=xueshu_se

**Comment by YiWeiHuang-stack** [comment]
跑题了
