### ISSUE TITLE
合并configure生产器与主程序

### ISSUE THREAD

**Issue by yxtj** [YiWeiHuang-stack/Squirrel-RIFE#4]
单独的一个配置生成器和主程序的分离毫无意义地增加了使用难度和成本，建议在界面内集成直接调用的按钮。

**Comment by ABlyh-LEO** [comment]
您的想法我们正在实现中，感谢您的支持

**Comment by yxtj** [comment]
希望你们能做到真正的开源，而不是把github当做软件发布平台。
