### ISSUE TITLE
界面显示只有输入帧率，没有输出帧率，在高级设置里面也没有调试选项！

### ISSUE THREAD

**Issue by gangirl** [YiWeiHuang-stack/Squirrel-RIFE#536]
<img width="722" alt="屏幕截图 2023-11-08 162556" src="https://github.com/Justin62628/Squirrel-RIFE/assets/147985853/f80a1c23-d483-4605-8236-9dd3626168ed">

**Comment by gangirl** [comment]
这个要怎么才能把输出帧率选项调出来呢

**Comment by routineLife1** [comment]
SAE仅为超分软件, 原帧率进原帧率出, 不支持改变帧率

**Comment by wondersure** [comment]
啊？SAE不是补帧软件么？

**Comment by boom-syndra** [comment]
> 啊？SAE不是补帧软件么？

补帧软件去下release中的SVFI，也挺好用

**Comment by wondersure** [comment]
Thanks发自我的手机-------- 原始邮件 --------发件人： boom-syndra ***@***.***>日期： 2024年6月5日周三 中午11:14收件人： Justin62628/Squirrel-RIFE ***@***.***>抄送： wondersure ***@***.***>, Comment ***@***.***>主    题： Re: [Justin62628/Squirrel-RIFE] 界面显示只有输入帧率，没有输出帧率，在高级设置里面也没有调试选项！ (Issue #536)

啊？SAE不是补帧软件么？

补帧软件去下release中的SVFI，也挺好用
