### ISSUE TITLE
请问下3.20.4怎么调用独显？

### ISSUE THREAD

**Issue by deadblue0910** [YiWeiHuang-stack/Squirrel-RIFE#538]
使用的cpu，显卡未占用
![Snipaste_2023-12-06_19-01-23](https://github.com/Justin62628/Squirrel-RIFE/assets/48860218/f817b092-460a-47bd-83d8-3d32c94434da)
![Snipaste_2023-12-06_19-01-36](https://github.com/Justin62628/Squirrel-RIFE/assets/48860218/1b250aec-1806-4d95-b7e2-c614fc6da5b6)
![Snipaste_2023-12-06_19-01-50](https://github.com/Justin62628/Squirrel-RIFE/assets/48860218/9b21a8aa-af4b-46e4-92ac-6363641fe945)
![Snipaste_2023-12-06_19-06-08](https://github.com/Justin62628/Squirrel-RIFE/assets/48860218/360d05b7-0b74-4261-b368-52ebd8c9054d)

**Comment by Justin62628** [comment]
ncnn模型使用3D性能，但由于是CPU编码所以CPU占用比较厉害。可以尝试使用cuda模型（不带ncnn的模型）以及硬件编码
