### ISSUE TITLE
根据一拍二一拍三规律，继续推理一拍四一直到一拍N

### ISSUE THREAD

**Issue by YiWeiHuang-stack** [YiWeiHuang-stack/Squirrel-RIFE#61]
或许可以考虑加入下列模式
1.或许可以用该算法标记一拍N区域后，对这些区域使用阈值除去重复帧，降低补帧难度，并避免人物嘴巴运动被异常去除的问题
2.识别一拍N算法在默认参数下保守且较为精确，但可能漏判，可以考虑使用帧差法辅助去重

**Comment by YiWeiHuang-stack** [comment]
换回旧的约束方法
if x - 1 not in opt and x + 1 not in opt and x not in opt:

**Comment by Justin62628** [comment]
SVFI 3.2.2/3 实现
