### ISSUE TITLE
SVFI3.1.1beta与3.2α 在开启NVENC编码+显存超量后，速度大幅度下降

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#77]
图忘记截了，因为测试的次数很多，直接说下观测到的结论吧
设备：2080Smax-Q+i7-10875H
显存占用用的GPU-Z，这玩意儿是实实在在计算显存占用的量，共享GPU内存非备用缓存的部分也会算进去
编码器如果选择QSV或者软编由于显存不会超标因此速度正常，补4K稳定在2.0-4.5的速度，显存占用6.5G
对于3.1.1beta，开启NVENC+去一拍N后，在初始阶段GPU占用为0，显存占用为7G（已关闭全部软件，启动前显存占用为300M），之后GPU占用稳定在100%，但是显存占用达到8.2G，超出了额定的7.8G（N卡默认200M硬件保留显存），速度为7-10秒每帧，显卡功耗仅为70W，表明有大量的开销是在显存与内存的交换中了。
对于3.2α，开启NVENC+去一拍三或者旧版去重后，在初始阶段GPU占用80%左右，功耗正常（稳定在max-q功耗上限105W），显存占用7.6G。随着补帧的进行出现一次显存占用升高至7.8G，随机速度骤降至7-10秒每帧。即使显存在之后回落至7.6G，速度也未恢复正常。
如果不开启去重，则由于显存占用稳定在7.5G及以下，并不会出现速度骤降的情况。

**Comment by Justin62628** [comment]
SVFI 3.3.0.alpha：需要更多观察
