### ISSUE TITLE
在选择保留中间文件的前提下，使用工具箱合并中间文件消失

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#80]
![image](https://user-images.githubusercontent.com/59187833/121038332-cb2a1080-c7e2-11eb-982c-bbd2328f8534.png)
![image](https://user-images.githubusercontent.com/59187833/121038352-d11ff180-c7e2-11eb-8f61-abd4fc04a4f2.png)
选择合并已有区块后，发现原文件夹区块已被删除

**Comment by Justin62628** [comment]
SVFI 3.2.2/3 修复
