### ISSUE TITLE
3.2α，4K NVENC 10bit输出时，间歇性出现QL降至0，显卡负载归0的情况

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#84]
![image](https://user-images.githubusercontent.com/59187833/121147679-ac278f00-c873-11eb-9c4d-e7bbd7b6bc28.png)
QL趋近于0

![image](https://user-images.githubusercontent.com/59187833/121152637-f6127400-c877-11eb-9893-561770d6d506.png)
GPU-Z监控到间歇性显卡占用为0的情况

![image](https://user-images.githubusercontent.com/59187833/121147826-d0836b80-c873-11eb-8a77-d270701ae502.png)
QL恢复后也仅在25-50之间的区间跳动

目前相同视频，使用其他压制策略并未出现类似情况
模型：anime_sharp 光流尺度：0.25

**Comment by Justin62628** [comment]
SVFI 3.3.0.alpha：需要更多观察
已优化4K ffmpeg压制导致的显卡占用问题
