### ISSUE TITLE
进度恢复改进方案

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#86]
可在每个trunk生成完成后，生成一个json文件存储该trunk的起始终止时间等信息（之所以不统一存在一个文件里是为了避免突然中断后导致的json文件损坏进度无法恢复的问题）。这样恢复进度时只需验证trunk完整性及读取最后一个trunk文件的信息即可。

**Comment by Justin62628** [comment]
3.2.2 已改善进度恢复的问题
