### ISSUE TITLE
视频有一半出现花屏

### ISSUE THREAD

**Issue by CangShui** [YiWeiHuang-stack/Squirrel-RIFE#90]
<a href="https://sm.ms/image/CXWUElavgM3iND9" target="_blank"><img src="https://i.loli.net/2021/06/25/CXWUElavgM3iND9.jpg" /></a>
也许是半精度模式的问题？

**Comment by Justin62628** [comment]
请告知使用的压制设置参数，欢迎来QQ群讨论。一般情况下使用软件编码可以解决此类压制问题

**Comment by Justin62628** [comment]
用CPU编码
