### ISSUE TITLE
关于暂停补帧后合并区块，无法恢复的问题

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#91]
![image](https://user-images.githubusercontent.com/59187833/123449304-1da26400-d60e-11eb-9f62-7feefb5e150a.png)
如标题所示，暂停补帧后选择合并已有区块，然后就恢复不了了。。。

**Comment by Justin62628** [comment]
补帧过程中不能使用工具箱功能
