### ISSUE TITLE
4kCG视频出现花屏现象

### ISSUE THREAD

**Issue by ZHENGLOC** [YiWeiHuang-stack/Squirrel-RIFE#92]
![QQ截图20210626053019](https://user-images.githubusercontent.com/24859848/123487237-18f6a380-d640-11eb-99c2-d6b280296360.png)
这个4k视频是Topaz Video Enhance AI超上去的，不知道是否有关，原视频720p没有出现花屏现象

**Comment by Justin62628** [comment]
如果不是SVFI的问题，欢迎进QQ群讨论
