### ISSUE TITLE
以下几个选项重启应用后会恢复默认，建议按照上次设置选择

### ISSUE THREAD

**Issue by yhrbjsy** [YiWeiHuang-stack/Squirrel-RIFE#99]
![image](https://user-images.githubusercontent.com/59187833/123548063-dc3cc080-d795-11eb-8332-7a1f03492c25.png)
![image](https://user-images.githubusercontent.com/59187833/123548071-e2cb3800-d795-11eb-84f2-3cae6c0bc7a6.png)
![image](https://user-images.githubusercontent.com/59187833/123548077-e78fec00-d795-11eb-8a9a-5fae563f8c19.png)

**Comment by Justin62628** [comment]
已更新于SVFI 3.3.0 alpha
